import { paginationQuery, seasonEnum } from '../../utils/validate.js';

// POST /wardrobe/items — accepts multipart/form-data with the image file
// The backend uploads the image to Supabase 'wardrobe' bucket and creates the DB record
export const createItemSchema = {
    body: {
        type: 'object',
        required: ['item_id'],
        properties: {
            // item_id is generated by mobile BEFORE the request
            item_id: { type: 'string', format: 'uuid' },
            name: { type: 'string', maxLength: 100 },
            brand: { type: 'string', maxLength: 100 },
            condition: { type: 'string', enum: ['new', 'like_new', 'good', 'fair', 'poor'] },
            purchase_price: { type: 'string' }, // multipart sends numbers as strings
            file: { type: 'object' },           // the raw image file buffer
        },
        additionalProperties: false,
    },
};

// PATCH /wardrobe/items/:id — update an existing item
export const updateItemSchema = {
    body: {
        type: 'object',
        properties: {
            name: { type: 'string', maxLength: 100 },
            brand: { type: 'string', maxLength: 100 },
            wardrobe_slot: {
                type: 'string',
                enum: ['upperwear', 'outerwear', 'lowerwear', 'dresses', 'footwear', 'accessories']
            },
            subcategory: { type: 'string', maxLength: 100 },
            colors: { type: 'array', items: { type: 'string', maxLength: 50 }, maxItems: 5 },
            pattern: { type: 'string', maxLength: 50 },
            fit: { type: 'string', enum: ['slim', 'regular', 'relaxed', 'oversized'] },
            season: seasonEnum,
            condition: { type: 'string', enum: ['new', 'like_new', 'good', 'fair', 'poor'] },
            purchase_price: { type: 'number', minimum: 0 },
            is_favourite: { type: 'boolean' },
            is_for_sale: { type: 'boolean' },
            resale_price: { type: 'number', minimum: 0 },
        },
        additionalProperties: false,
    },
};

// POST /wardrobe/items/batch — accepts multipart/form-data with multiple image files
// item_ids is a JSON-encoded array of UUIDs; file field is repeated once per image
export const batchCreateItemsSchema = {
    body: {
        type: 'object',
        required: ['item_ids'],
        properties: {
            item_ids: { type: 'string' }, // JSON array of UUIDs, e.g. '["uuid1","uuid2"]'
            file: {},                      // Buffer or Buffer[] — skips strict type validation
        },
        additionalProperties: false,
    },
};

// GET /wardrobe/items — list with filters and pagination
export const listItemsSchema = {
    querystring: {
        type: 'object',
        properties: {
            slot: { type: 'string', enum: ['upperwear', 'outerwear', 'lowerwear', 'dresses', 'footwear', 'accessories'] },
            season: seasonEnum,
            is_favourite: { type: 'boolean' },
            is_for_sale: { type: 'boolean' },
            ...paginationQuery,
        },
        additionalProperties: false,
    },
};
