// POST /wardrobe/items — create a new wardrobe item after image upload
export const createItemSchema = {
    body: {
        type: 'object',
        required: ['item_id', 'image_path'],
        properties: {
            // item_id is generated by mobile BEFORE upload
            item_id: { type: 'string', format: 'uuid' },
            image_path: { type: 'string', minLength: 1, maxLength: 500 },
            name: { type: 'string', maxLength: 100 },
            brand: { type: 'string', maxLength: 100 },
            // Optional manual overrides — AI fills these if not provided
            category: {
                type: 'string', enum: [
                    'tops', 'bottoms', 'dresses', 'outerwear', 'footwear',
                    'accessories', 'activewear', 'swimwear', 'underwear', 'sleepwear',
                ]
            },
            condition: { type: 'string', enum: ['new', 'like_new', 'good', 'fair', 'poor'] },
            purchase_price: { type: 'number', minimum: 0 },
        },
        additionalProperties: false,
    },
};

// PATCH /wardrobe/items/:id — update an existing item
export const updateItemSchema = {
    body: {
        type: 'object',
        properties: {
            name: { type: 'string', maxLength: 100 },
            brand: { type: 'string', maxLength: 100 },
            category: {
                type: 'string', enum: [
                    'tops', 'bottoms', 'dresses', 'outerwear', 'footwear',
                    'accessories', 'activewear', 'swimwear', 'underwear', 'sleepwear',
                ]
            },
            subcategory: { type: 'string', maxLength: 100 },
            colors: { type: 'array', items: { type: 'string' }, maxItems: 5 },
            pattern: { type: 'string', maxLength: 50 },
            fit: { type: 'string', enum: ['slim', 'regular', 'relaxed', 'oversized'] },
            season: { type: 'string', enum: ['spring', 'summer', 'autumn', 'winter', 'all_season'] },
            condition: { type: 'string', enum: ['new', 'like_new', 'good', 'fair', 'poor'] },
            purchase_price: { type: 'number', minimum: 0 },
            is_favourite: { type: 'boolean' },
            is_for_sale: { type: 'boolean' },
            resale_price: { type: 'number', minimum: 0 },
        },
        additionalProperties: false,
    },
};

// GET /wardrobe/items — list with filters and pagination
export const listItemsSchema = {
    querystring: {
        type: 'object',
        properties: {
            category: { type: 'string' },
            season: { type: 'string' },
            is_favourite: { type: 'boolean' },
            is_for_sale: { type: 'boolean' },
            page: { type: 'integer', minimum: 1, default: 1 },
            limit: { type: 'integer', minimum: 1, maximum: 50, default: 20 },
        },
        additionalProperties: false,
    },
};
